server.port=8080

spring.application.name=event-gateway-service

account.service.base-url=http://localhost:8081

management.endpoints.web.exposure.include=health,metrics,circuitbreakers,circuitbreakerevents
management.endpoint.health.show-details=always
spring.datasource.url=jdbc:h2:mem:event_gateway_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

logging.level.root=INFO

logging.pattern.console=%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} level=%level service=${spring.application.name} traceId=%X{traceId} thread=%thread logger=%logger{36} message="%msg"%n


resilience4j.circuitbreaker.instances.accountServiceCircuitBreaker.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.accountServiceCircuitBreaker.minimum-number-of-calls=3
resilience4j.circuitbreaker.instances.accountServiceCircuitBreaker.sliding-window-size=5
resilience4j.circuitbreaker.instances.accountServiceCircuitBreaker.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.accountServiceCircuitBreaker.permitted-number-of-calls-in-half-open-state=2

resilience4j.timelimiter.instances.accountServiceCircuitBreaker.timeout-duration=2s